### ISSUE TITLE
Why I prepare the dataset but turned out error

### ISSUE THREAD

**Issue by whyydsforever** [tqxli/breast_ultrasound_lesion_segmentation_PyTorch#3]
Traceback (most recent call last):
  File "train.py", line 71, in <module>
    main(config)
  File "train.py", line 56, in main
    trainer.train()
  File "D:\FYP\breast_ultrasound_lesion_segmentation_PyTorch-main\base\base_trainer.py", line 63, in train
    result = self._train_epoch(epoch)
  File "D:\FYP\breast_ultrasound_lesion_segmentation_PyTorch-main\trainer\trainer.py", line 41, in _train_epoch
    for batch_idx, (data, target) in enumerate(self.data_loader):
  File "C:\Users\wu\.conda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\Users\wu\.conda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\wu\.conda\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\wu\.conda\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\FYP\breast_ultrasound_lesion_segmentation_PyTorch-main\dataloader\preprocessor.py", line 58, in __getitem__
    mask = cv2.imread(os.path.join(self.masks_dir, img_filename), cv2.IMREAD_GRAYSCALE).astype(np.float32) # [H, W]
AttributeError: 'NoneType' object has no attribute 'astype'

**Comment by tqxli** [comment]
`AttributeError: 'NoneType' object has no attribute 'astype' ` usually means that there exists no image in the specified directory. I'll recommend double check `os.path.join(self.masks_dir, img_filename)`.
